services:
  find-my-kids:
    container_name: find-my-kids
    image: techblog/find-my-kids:latest
    ports:
      - "7020:7020"
    environment:
      - GREEN_API_INSTANCE=${GREEN_API_INSTANCE}
      - GREEN_API_TOKEN=${GREEN_API_TOKEN}
      - PROBABILITY_THRESHOLD=0.5
    volumes:
      - ./find-my-kids/images:/app/images
      - ./find-my-kids/config:/app/config
      - ./find-my-kids/classifiers:/app/classifiers
    restart: unless-stopped 