services:
  app:
    image: techblog/find-my-kids:latest
    ports:
      - "7020:7020"
    environment:
      - GREEN_API_INSTANCE=${GREEN_API_INSTANCE}
      - GREEN_API_TOKEN=${GREEN_API_TOKEN}
    volumes:
      - ./find-my-kids/images:/app/images
      - ./find-my-kids/config:/app/config
      - ./find-my-kids/classifiers:/app/classifiers
    restart: unless-stopped 